export const COURSES_DATA = [
  {
    id: 1,
    title: "MMI-DESIGN-GRAPHIQUE-FONDAMENTAUX",
    code: "MMIDG1",
    documents: 15,
    announcements: 3,
    buttonColor: "red",
    borderColor: "red",
  },
  {
    id: 2,
    title: "MMI-TYPOGRAPHIE-ET-MISE-EN-PAGE",
    code: "MMITYPO",
    documents: 12,
    announcements: 5,
    image: "/api/placeholder/100/100",
    buttonColor: "blue",
    borderColor: "blue",
  },
  {
    id: 3,
    title: "MMI-DESIGN-INTERFACE-UI-UX",
    code: "MMIUI",
    documents: 18,
    announcements: 7,
    image: "/api/placeholder/100/100",
    buttonColor: "red",
    borderColor: "red",
  },
  {
    id: 4,
    title: "MMI-MOTION-DESIGN-ANIMATION",
    code: "MMIMOTION",
    documents: 20,
    announcements: 4,
    buttonColor: "blue",
    borderColor: "blue",
  },
  {
    id: 5,
    title: "MMI-IDENTITE-VISUELLE-BRANDING",
    code: "MMIBRAND",
    documents: 10,
    announcements: 6,
    image: "/api/placeholder/100/100",
    buttonColor: "red",
    borderColor: "red",
  },
  {
    id: 6,
    title: "MMI-ILLUSTRATION-DIGITALE",
    code: "MMIILLUS",
    documents: 16,
    announcements: 2,
    buttonColor: "blue",
    borderColor: "blue",
  },
  {
    id: 7,
    title: "MMI-PHOTOGRAPHIE-NUMERIQUE",
    code: "MMIPHOTO",
    documents: 14,
    buttonColor: "red",
    borderColor: "red",
    hasInfo: true,
    hasNotification: true,
  },
  {
    id: 8,
    title: "MMI-DESIGN-3D-MODELISATION",
    code: "MMI3D",
    documents: 22,
    image: "/api/placeholder/100/100",
    buttonColor: "blue",
    borderColor: "blue",
    hasInfo: true,
  },
  {
    id: 9,
    title: "MMI-PROJET-DESIGN-STUDIO",
    code: "MMISTUDIO",
    documents: 8,
    announcements: 9,
    buttonColor: "red",
    borderColor: "red",
    hasNotification: true,
  },
];
